Meta:
  SchemaVersion: 3
Telemetry:
  CollectBackupLog: true
Backups:
  - ID: Consul
    Source:
      Consul:
        Addr: http://127.0.0.1:8500
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/consul.snap
